### ISSUE TITLE
Message to get latest version

### ISSUE THREAD

**Issue by UkieBoar** [kwerty/Gmail-Notifier#12]
I've downloaded and installed the latest version available of the notifier from kwerty.com.
Each time the notifier launches, I get the message to get the latest version from kwerty.com.

Very annoying to continuously get that message.....

**Comment by kwerty** [comment]
Hi UkieBoar, thank you very much for reporting this. I completely forgot I'd put that in there, and as I do not restart my computer very often I wasn't seeing the message.

I've removed the expiry/nag screen permanently so this never happens again.

http://kwerty.com/Gmail-Notifier-for-Windows-7/Kwerty-Gmail-Notifier-1_5.exe

**Comment by UkieBoar** [comment]
Thanks!

On Thu, Jan 8, 2015 at 4:04 PM, kwerty notifications@github.com wrote:

> Closed #12 https://github.com/kwerty/Gmail-Notifier/issues/12.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kwerty/Gmail-Notifier/issues/12#event-216160557.

## 

Markian
